import { StyleSheet } from "@react-pdf/renderer";

import { PDF_RADIUS } from "@/lib/pdf/radius";

/** Palette sobre — excellent rendu impression N&B */
export const pdfColors = {
  ink: "#0f172a",
  inkMuted: "#475569",
  inkLight: "#64748b",
  border: "#e2e8f0",
  borderStrong: "#cbd5e1",
  surface: "#f8fafc",
  surfaceMuted: "#f1f5f9",
  accent: "#1e293b",
  white: "#ffffff",
  danger: "#b91c1c",
  dangerBg: "#fef2f2",
  warningBg: "#f8fafc",
} as const;

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 9,
    paddingTop: 32,
    paddingBottom: 52,
    paddingHorizontal: 48,
    color: pdfColors.ink,
    lineHeight: 1.4,
    backgroundColor: pdfColors.white,
  },
  pageBody: {
    flexDirection: "column",
  },

  accentBar: {
    height: 2,
    backgroundColor: pdfColors.accent,
    marginBottom: 14,
    borderRadius: 2,
  },

  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
    gap: 22,
  },
  headerLeft: {
    flex: 1,
    maxWidth: "52%",
  },
  headerRight: {
    flex: 1,
    maxWidth: "48%",
    alignItems: "flex-end",
  },
  logoWrap: {
    marginBottom: 6,
    padding: 4,
    backgroundColor: pdfColors.surface,
    borderWidth: 1,
    borderColor: pdfColors.border,
    borderRadius: PDF_RADIUS,
    alignSelf: "flex-start",
  },
  logo: {
    maxWidth: 108,
    maxHeight: 40,
    objectFit: "contain",
  },
  headerCompanyName: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.ink,
    marginBottom: 1,
  },
  headerCompanySubtitle: {
    fontSize: 7,
    color: pdfColors.inkMuted,
    lineHeight: 1.3,
  },
  invoiceEyebrow: {
    fontSize: 6,
    color: "#94a3b8",
    letterSpacing: 1.4,
    textTransform: "uppercase",
    marginBottom: 4,
    textAlign: "right",
  },
  invoiceNumber: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.ink,
    textAlign: "right",
    letterSpacing: -0.2,
    marginBottom: 10,
  },
  metaBlock: {
    width: "100%",
    borderWidth: 1,
    borderColor: pdfColors.border,
    borderRadius: PDF_RADIUS,
    backgroundColor: pdfColors.surface,
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 2,
  },
  metaLabel: {
    fontSize: 8,
    color: pdfColors.inkLight,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  metaValue: {
    fontSize: 8,
    color: pdfColors.ink,
    textAlign: "right",
    maxWidth: "62%",
  },

  draftBanner: {
    backgroundColor: pdfColors.warningBg,
    borderWidth: 1,
    borderColor: pdfColors.borderStrong,
    borderRadius: 4,
    paddingVertical: 7,
    paddingHorizontal: 10,
    marginBottom: 12,
  },
  draftBannerTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 10,
    color: pdfColors.ink,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 3,
    textAlign: "center",
  },
  draftBannerText: {
    fontSize: 8,
    color: pdfColors.inkMuted,
    lineHeight: 1.4,
    textAlign: "center",
  },
  draftWatermark: {
    position: "absolute",
    top: 320,
    left: 48,
    right: 48,
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.07,
  },
  draftWatermarkText: {
    fontSize: 64,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.ink,
    letterSpacing: 12,
    textTransform: "uppercase",
  },
  cancelledBanner: {
    backgroundColor: pdfColors.dangerBg,
    borderWidth: 1,
    borderColor: pdfColors.danger,
    borderRadius: 4,
    paddingVertical: 7,
    paddingHorizontal: 10,
    marginBottom: 12,
  },
  cancelledText: {
    color: pdfColors.danger,
    fontFamily: "Helvetica-Bold",
    fontSize: 10,
    textAlign: "center",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },

  partiesRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
    gap: 12,
  },
  partyBlock: {
    width: "48%",
    borderWidth: 1,
    borderColor: pdfColors.border,
    borderRadius: PDF_RADIUS,
    backgroundColor: pdfColors.surface,
    paddingVertical: 8,
    paddingHorizontal: 9,
  },
  partyLabel: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.inkLight,
    marginBottom: 5,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  partyName: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.ink,
    marginBottom: 2,
  },
  partySubtitle: {
    fontSize: 7,
    color: pdfColors.inkMuted,
    marginBottom: 4,
  },
  partySubsection: {
    marginTop: 6,
  },
  partySubsectionDivider: {
    height: 1,
    backgroundColor: pdfColors.border,
    marginBottom: 6,
  },
  partySubsectionLabel: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.inkLight,
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  partyLine: {
    fontSize: 7,
    color: pdfColors.inkMuted,
    marginBottom: 1,
    lineHeight: 1.3,
  },

  table: {
    marginBottom: 0,
    backgroundColor: pdfColors.white,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: pdfColors.surfaceMuted,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 0,
    borderColor: pdfColors.border,
    borderTopLeftRadius: PDF_RADIUS,
    borderTopRightRadius: PDF_RADIUS,
    paddingVertical: 6,
    paddingHorizontal: 11,
  },
  tableHeaderCell: {
    fontFamily: "Helvetica-Bold",
    fontSize: 7,
    color: pdfColors.inkLight,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 6,
    paddingHorizontal: 11,
    fontSize: 8,
    backgroundColor: pdfColors.white,
    borderWidth: 1,
    borderColor: pdfColors.border,
  },
  tableRowLast: {
    borderBottomLeftRadius: PDF_RADIUS,
    borderBottomRightRadius: PDF_RADIUS,
  },
  colDesc: { width: "38%", paddingRight: 8 },
  colDescText: { color: pdfColors.ink, lineHeight: 1.4 },
  colQty: { width: "10%" },
  colPu: { width: "14%" },
  colVat: { width: "10%" },
  colHt: { width: "14%" },
  colTtc: { width: "14%" },
  colCellLeft: {
    textAlign: "left",
  },
  colCellCenter: {
    textAlign: "center",
    color: pdfColors.inkMuted,
  },
  colHeaderCenter: {
    textAlign: "center",
  },
  colHeaderRight: {
    textAlign: "right",
  },
  colCellRight: {
    textAlign: "right",
    color: pdfColors.inkMuted,
  },
  colCellRightBold: {
    textAlign: "right",
    fontFamily: "Helvetica-Bold",
    color: pdfColors.ink,
  },

  closingSection: {
    flexDirection: "column",
    marginTop: 22,
  },

  totalsBlockRoot: {
    marginTop: 0,
  },

  totalsSection: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginBottom: 0,
  },
  totalsBox: {
    width: 272,
    borderWidth: 1,
    borderColor: pdfColors.border,
    borderRadius: PDF_RADIUS,
    overflow: "hidden",
    backgroundColor: pdfColors.white,
  },
  totalsHeader: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.border,
    borderTopLeftRadius: PDF_RADIUS,
    borderTopRightRadius: PDF_RADIUS,
    backgroundColor: pdfColors.surfaceMuted,
  },
  totalsHeaderText: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.inkLight,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  totalsBody: {
    paddingTop: 6,
    paddingBottom: 6,
    paddingHorizontal: 14,
    backgroundColor: pdfColors.surface,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 3,
    gap: 10,
  },
  totalLabel: {
    fontSize: 8,
    color: pdfColors.ink,
  },
  totalLabelFlex: {
    flex: 1,
    paddingRight: 8,
  },
  totalLabelMuted: {
    fontSize: 8,
    color: pdfColors.inkMuted,
  },
  totalValue: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.ink,
    textAlign: "right",
    minWidth: 72,
  },
  totalDivider: {
    height: 1,
    backgroundColor: pdfColors.border,
    marginVertical: 4,
  },
  totalsTtcBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: pdfColors.accent,
    paddingVertical: 9,
    paddingHorizontal: 14,
  },
  totalsTtcBarRoundedBottom: {
    borderBottomLeftRadius: PDF_RADIUS,
    borderBottomRightRadius: PDF_RADIUS,
  },
  totalTtcLabel: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.white,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  totalTtcValue: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.white,
  },

  footerBlockFirst: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
  },
  footerBlockNext: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
  },
  footerTitle: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.inkLight,
    marginBottom: 5,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  footerText: {
    fontSize: 8,
    color: pdfColors.inkMuted,
    lineHeight: 1.45,
  },
  legalMentions: {
    fontSize: 7,
    color: pdfColors.inkLight,
    lineHeight: 1.5,
  },
  legalMentionsDefault: {
    fontSize: 7,
    color: pdfColors.inkLight,
    lineHeight: 1.45,
  },
  pageFooterFixed: {
    position: "absolute",
    bottom: 18,
    left: 44,
    right: 44,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
    paddingTop: 8,
  },
  pageNumberText: {
    fontSize: 7,
    color: pdfColors.inkLight,
  },

  acceptanceSection: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: pdfColors.borderStrong,
  },
  acceptanceTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.ink,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  acceptanceDivider: {
    height: 1,
    backgroundColor: pdfColors.border,
    marginBottom: 10,
  },
  acceptanceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 6,
  },
  acceptanceLabel: {
    fontSize: 8,
    color: pdfColors.inkLight,
    width: 72,
  },
  acceptanceValue: {
    flex: 1,
    fontSize: 9,
    color: pdfColors.ink,
    textAlign: "right",
  },
  acceptanceSignatureWrap: {
    marginTop: 8,
  },
  acceptanceSignatureImage: {
    marginTop: 6,
    width: 180,
    height: 64,
    objectFit: "contain",
    objectPosition: "left",
  },

  receiptPage: {
    fontFamily: "Helvetica",
    fontSize: 9,
    paddingTop: 34,
    paddingBottom: 36,
    paddingHorizontal: 48,
    color: pdfColors.ink,
    lineHeight: 1.4,
    backgroundColor: pdfColors.white,
  },
  receiptPageBody: {
    flexDirection: "column",
  },
  receiptHero: {
    alignItems: "center",
    marginBottom: 16,
  },
  receiptTitle: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.ink,
    textTransform: "uppercase",
    letterSpacing: 1.4,
    textAlign: "center",
  },
  receiptSubtitle: {
    fontSize: 9,
    color: pdfColors.inkMuted,
    marginTop: 8,
    textAlign: "center",
    lineHeight: 1.35,
  },
  receiptPaidBadge: {
    marginTop: 12,
    backgroundColor: "#ecfdf5",
    borderWidth: 1,
    borderColor: "#34d399",
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 16,
  },
  receiptPaidBadgeText: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: "#047857",
    textTransform: "uppercase",
    letterSpacing: 1,
    textAlign: "center",
  },
  receiptSection: {
    marginBottom: 14,
  },
  receiptPartiesSection: {
    marginBottom: 14,
  },
  receiptSectionTitle: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.inkLight,
    textTransform: "uppercase",
    letterSpacing: 0.9,
    marginBottom: 6,
  },
  receiptHighlightBlock: {
    borderWidth: 1,
    borderColor: pdfColors.borderStrong,
    borderRadius: PDF_RADIUS,
    backgroundColor: pdfColors.surface,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  receiptMetaBlock: {
    borderWidth: 1,
    borderColor: pdfColors.border,
    borderRadius: PDF_RADIUS,
    backgroundColor: pdfColors.white,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  receiptMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
    gap: 12,
  },
  receiptMetaDivider: {
    height: 1,
    backgroundColor: pdfColors.border,
    marginVertical: 4,
  },
  receiptMetaLabel: {
    fontSize: 8,
    color: pdfColors.inkLight,
    fontFamily: "Helvetica-Bold",
    width: "40%",
  },
  receiptMetaValue: {
    fontSize: 8,
    color: pdfColors.ink,
    textAlign: "right",
    flex: 1,
    lineHeight: 1.35,
  },
  receiptAmountValue: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.ink,
  },
  receiptClosingBlock: {
    marginTop: 2,
  },
  receiptTechSection: {
    marginBottom: 10,
  },
  receiptTechTitle: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.inkLight,
    textTransform: "uppercase",
    letterSpacing: 0.7,
    marginBottom: 6,
  },
  receiptTechBlock: {
    borderWidth: 1,
    borderColor: pdfColors.border,
    borderRadius: PDF_RADIUS,
    backgroundColor: pdfColors.surfaceMuted,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  receiptTechDivider: {
    height: 1,
    backgroundColor: pdfColors.border,
    marginVertical: 5,
  },
  receiptStripeRef: {
    gap: 3,
  },
  receiptStripeRefLabel: {
    fontSize: 7,
    color: pdfColors.inkLight,
    fontFamily: "Helvetica-Bold",
  },
  receiptStripeRefValue: {
    fontSize: 6.5,
    color: pdfColors.inkMuted,
    lineHeight: 1.45,
    fontFamily: "Helvetica",
  },
  receiptLegalBox: {
    borderWidth: 1,
    borderColor: pdfColors.border,
    borderRadius: PDF_RADIUS,
    backgroundColor: pdfColors.surface,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  receiptLegalText: {
    fontSize: 7,
    color: pdfColors.inkLight,
    lineHeight: 1.45,
    textAlign: "center",
  },
  receiptFooterInline: {
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  receiptFooterText: {
    fontSize: 7,
    color: pdfColors.inkLight,
  },
  depositSection: {
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: pdfColors.border,
    borderRadius: PDF_RADIUS,
    backgroundColor: pdfColors.surface,
    gap: 4,
  },
  depositSectionTitle: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.ink,
    marginBottom: 2,
  },
  depositRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
  },
  depositLabel: {
    fontSize: 7.5,
    color: pdfColors.inkMuted,
  },
  depositValue: {
    fontSize: 7.5,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.ink,
  },
  depositPaidBadge: {
    marginTop: 6,
    alignSelf: "flex-start",
    backgroundColor: "#ecfdf5",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  depositPaidBadgeText: {
    fontSize: 7,
    color: "#047857",
    fontFamily: "Helvetica-Bold",
  },
});
